version: '{build}'

branches:
only:
- master

init:
- git config --global core.autocrlf input

skip_tags: true
shallow_clone: true
clone_depth: 1

environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
    QT5: C:\Qt\5.7\msvc2015_64
    VSVER: 14
  - CMAKE_GENERATOR: "MinGW Makefiles"
    QT5: C:\Qt\5.7\mingw53_32
    MINGW_PATH: C:\Qt\Tools\mingw530_32\bin


before_build:
  - set Path=%QT5%\bin;%Path%
  - if "%CMAKE_GENERATOR%" == "MinGW Makefiles" set PATH=%MINGW_PATH%\bin;%PATH:C:\Program Files\Git\usr\bin;=%

build:

build_script:
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - if NOT "%CMAKE_GENERATOR%" == "MinGW Makefiles" echo "Using Visual Studio %VSVER%.0 at %VSCOMNTOOLS%"
  - if "%CMAKE_GENERATOR%" == "MinGW Makefiles" echo "Using MinGW at %MINGW_PATH%"
  - md build
  - cd build
  - cmake .. -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%QT5%"
  - cmake --build . --config Release