version: '{build}'

init:
- git config --global core.autocrlf true

skip_tags: true
shallow_clone: true
clone_depth: 1

environment:
  QTDIR: C:\Qt\5.7\mingw53_32

install:
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%

build_script:
  - qmake CONFIG+=release Wisetagger.pro
  - mingw32-make

