version: '{build}'

init:
- git config --global core.autocrlf true

skip_tags: true
shallow_clone: true
clone_depth: 1

environment:
  matrix:
  - CMAKE_GENERATOR: "MinGW Makefiles"
    QT5: C:\Qt\5.7\mingw53_32
    MINGW_PATH: C:\Qt\Tools\mingw530_32\bin


before_build:
  - set Path=%QT5%\bin;%Path%
  - if "%CMAKE_GENERATOR%" == "MinGW Makefiles" set PATH=%MINGW_PATH%\bin;%PATH:C:\Program Files\Git\usr\bin;=%

build:

build_script:
  - if "%CMAKE_GENERATOR%" == "MinGW Makefiles" echo "Using MinGW at %MINGW_PATH%"
  - md build
  - cd build
  - cmake .. -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%QT5%"
  - cmake --build . --config Release
