version: '{build}'

init:
- git config --global core.autocrlf true

skip_tags: true
shallow_clone: true
clone_depth: 1

environment:
  QTDIR: C:\Qt\5.13.2\mingw73_64
  MINGWDIR: C:\Qt\Tools\mingw730_64

install:
  - set PATH=%QTDIR%\bin;%MINGWDIR%\bin;%PATH%

build_script:
  - qmake CONFIG+=release Wisetagger.pro
  - mingw32-make

