language: cpp

os:
  - linux

dist: bionic

git:
  depth: 3

install:
  - lsb_release -a
  - sudo apt-add-repository -y ppa:beineri/opt-qt-5.14.1-bionic
  - sudo apt-get -qq update
  - sudo apt-get -qq install qt514tools qt514base qt514svg qt514imageformats qt514translations qt514multimedia libgl1 libgl1-mesa-dev

script:
  - QTDIR="/opt/qt514"
  - PATH="$QTDIR/bin:$PATH"
  - qt514-env.sh
  - qmake CONFIG+=release
  - make
