language: cpp

os:
  - linux

dist: trusty

git:
  depth: 3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

install:
  - lsb_release -a
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 60
  - sudo apt-add-repository -y ppa:beineri/opt-qt58-trusty
  - sudo apt-get -qq update
  - sudo apt-get -qq install qt58tools qt58base qt58svg qt58imageformats qt58translations

script:
  - QTDIR="/opt/qt58"
  - PATH="$QTDIR/bin:$PATH"
  - qt58-env.sh
  - qmake CONFIG+=release
  - make
