language: cpp

os:
  - linux

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: 
        - COMPILER=g++-6
        - CONFIG=release

install:
  - lsb_release -a
  - sudo apt-add-repository -y ppa:beineri/opt-qt562
  - sudo apt-get -qq update
  - sudo apt-get -qq install qt56tools qt56base qt56svg qt56imageformats qt56translations

script:
  - QTDIR="/opt/qt56"
  - PATH="$QTDIR/bin:$PATH"
  - qt56-env.sh
  - export CXX="$COMPILER"
  - $CXX --version
  - qmake
  - make
